controllers:
  resource: ../src/Controller/
  type: attribute
# config/routes.yaml


registro_usuario:
  path: /usuario/registro
  controller: App\Controller\UsuarioController::registro

registro_admin:
  path: /usuario/registro_admin
  controller: App\Controller\AdminController::registro_admin
  
admin_vista:
  path: /usuario/tabla_Admin
  controller: App\Controller\AdminController::obtenerUsuariosAdmin

eliminar_usuario:
  path: /usuario/borrar
  controller: App\Controller\AdminController::eliminarUsuario

login_usuario:
  path: /usuario/login
  controller: App\Controller\UsuarioController::login

perfil_usuario:
  path: /usuario/editarPerfil
  controller: App\Controller\UsuarioController::editarPerfil

contraseña_usuario:
  path: /usuario/cambiarContrasena
  controller: App\Controller\UsuarioController::cambiarContraseña

nueva_incidencia:
  path: /incidencia/registrar
  controller: App\Controller\IncidenciaController::nuevaIncidencia
  
listar_incidencia_cliente:
  path: /incidencia/ver-cliente
  controller: App\Controller\IncidenciaController::listarIncidenciasUsuario

listar_incidencia_trabajador:
  path: /incidencia/ver-trabajador
  controller: App\Controller\IncidenciaController::listarIncidenciasEmpleado

listar_incidencia_trabajador2:
  path: /incidencia/ver-trabajador2
  controller: App\Controller\IncidenciaController::listarIncidenciasEmpleado2

actualizar_incidencia:
  path: /incidencia/actualizar
  controller: App\Controller\IncidenciaController::actualizarIncidencia

actualizar_incidencia2:
  path: /incidencia/actualizar2
  controller: App\Controller\IncidenciaController::actualizarIncidencia2
  
incidencia_historico:
  path: /incidencias/historico
  controller: App\Controller\IncidenciaController::listarHistorialIncidencias
 
actualizar_contrasenya:
  path: /usuario/resetpassword
  controller: App\Controller\UsuarioController::resetpassword

enviar_correo:
  path: /usuario/enviarcorreo
  controller: App\Controller\UsuarioController::enviarcorreo


